import '@/styles/base/globals.scss';
import type { Metadata } from 'next';
import Header from '@/components/header/Header';
import {
  IBMPlexMono,
  lobster,
  mansalva,
  megrim,
  permanentMarker,
} from '../../public/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="ko"
      className={`
      ${mansalva.variable} 
      ${megrim.variable} 
      ${lobster.variable} 
      ${permanentMarker.variable} 
      ${IBMPlexMono.variable}`}
    >
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
