import '@/styles/base/globals.scss';
import type { Metadata } from 'next';
import { dir } from 'i18next';
import Header from '@/components/header/Header';
import LanguageSwitchButton from '@/components/language-button/LanguageSwitchButton';
import {
  IBMPlexMono,
  lobster,
  mansalva,
  megrim,
  permanentMarker,
} from '../../../public/fonts';
import { languages } from '../i18n/settings';

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: { lng: string };
}

export default function RootLayout({ children, params: { lng } }: RootLayoutProps) {
  return (
    <html
      lang={lng}
      dir={dir(lng)}
      className={`
      ${mansalva.variable} 
      ${megrim.variable} 
      ${lobster.variable} 
      ${permanentMarker.variable} 
      ${IBMPlexMono.variable}`}
    >
      <body>
        <LanguageSwitchButton lng={lng} />
        <Header />
        {children}
      </body>
    </html>
  );
}
