import '@/styles/base/globals.scss';
import 'react-notion-x/src/styles.css';
import type { Metadata } from 'next';
import { dir } from 'i18next';
import Header from '@/components/layouts/header/Header';
import { LngParamsProps } from '@/types/lngSwitch';
import {
  IBMPlexMono,
  lobster,
  mansalva,
  megrim,
  permanentMarker,
  solway,
  balooBhaina,
  chakraPatch,
  spaceMono,
} from '../../../public/fonts/fonts';
import { languages } from '../i18n/settings';

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

export const revalidate = 3600 * 6;

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps extends LngParamsProps {
  children: React.ReactNode;
}

export default function RootLayout({ children, params: { lng } }: RootLayoutProps) {
  const fontVariables = `
  ${mansalva.variable} 
  ${megrim.variable} 
  ${lobster.variable} 
  ${permanentMarker.variable} 
  ${solway.variable} 
  ${balooBhaina.variable} 
  ${chakraPatch.variable} 
  ${spaceMono.variable} 
  ${IBMPlexMono.variable}`;

  return (
    <html lang={lng} dir={dir(lng)} className={fontVariables}>
      <body>
        <Header lng={lng} />
        {children}
      </body>
    </html>
  );
}
